# Generated by Django 3.0.7 on 2020-09-25 15:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=75, unique=True)),
                ('related_profession_name', models.CharField(max_length=75)),
                ('department_image', models.ImageField(upload_to='department_pics')),
                ('short_description', models.CharField(max_length=75)),
            ],
        ),
        migrations.CreateModel(
            name='doctors',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=75)),
                ('last_name', models.CharField(max_length=75)),
                ('image', models.ImageField(upload_to='doctors_pic')),
                ('email', models.CharField(max_length=75)),
                ('city', models.CharField(max_length=75)),
                ('password', models.CharField(max_length=32)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], default='Nothing', max_length=15)),
                ('age', models.IntegerField(default=0)),
                ('profession', models.CharField(choices=[('Neurologist', 'Neurologist'), ('Gynecologist', 'Gynecologist'), ('Dentist', 'Dentist')], max_length=75)),
                ('hospital', models.CharField(max_length=75)),
            ],
        ),
        migrations.CreateModel(
            name='patient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=75)),
                ('username', models.CharField(default='Nothing', max_length=75)),
                ('last_name', models.CharField(max_length=75)),
                ('email', models.CharField(max_length=75)),
                ('password', models.CharField(max_length=32)),
                ('gender', models.CharField(default='Nothing', max_length=15)),
                ('age', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='fakes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_fake', models.BooleanField(default=True)),
                ('USER', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='application.patient')),
            ],
        ),
        migrations.CreateModel(
            name='doctor_review',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('review_star', models.IntegerField()),
                ('review_msg', models.TextField()),
                ('date', models.DateField(default='2020-09-25')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='application.patient')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='application.doctors')),
            ],
        ),
        migrations.CreateModel(
            name='doctor_leave',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leave_date', models.DateField()),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='application.doctors')),
            ],
        ),
        migrations.CreateModel(
            name='Chats',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(blank=True, null=True)),
                ('time', models.TimeField(auto_now=True)),
                ('date', models.DateField(auto_now=True)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receiver', to=settings.AUTH_USER_MODEL)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sender', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date', '-time'],
            },
        ),
        migrations.CreateModel(
            name='appointment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('depart', models.CharField(max_length=50)),
                ('appointment_date', models.DateField(blank=True, null=True)),
                ('appointment_time', models.TimeField(blank=True, null=True)),
                ('status', models.IntegerField(default=0)),
                ('sender_patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='application.patient')),
                ('to_doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='application.doctors')),
            ],
        ),
    ]
