# Generated by Django 3.0.7 on 2020-09-25 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0004_auto_20200925_1616'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='selfie',
            field=models.ImageField(null=True, upload_to='images'),
        ),
    ]
