# Generated by Django 3.0.7 on 2020-09-26 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0005_patient_selfie'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor_review',
            name='date',
            field=models.DateField(default='2020-09-26'),
        ),
    ]
