# Generated by Django 3.1.1 on 2020-09-27 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0006_auto_20200926_0640'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor_review',
            name='date',
            field=models.DateField(default='2020-09-27'),
        ),
        migrations.AlterField(
            model_name='doctors',
            name='profession',
            field=models.CharField(choices=[('Neurologist', 'Neurologist'), ('Gynecologist', 'Gynecologist'), ('Dentist', 'Dentist'), ('Cardiologist', 'Cardiologist'), ('Covid Specialist', 'Covid Specialist')], max_length=75),
        ),
    ]
